class DataSalesConst {
  static final List<String> listarea = [
    "KOTA+SDA",
    "SBY OUT",
    "NTT",
    "MALANG",
    "JEMBER",
    "NTB",
    "KALSEL",
    "KALTENG",
    "KALTIM",
    "KALTARA"
  ];

  static final List<String> rangeUM = [
    "TUNAI",
    "<=10%",
    "10%-15%",
    "15%-20%",
    "20%-25%",
    "25%-30%",
    ">30%",
  ];

  static final List<String> Mktkategori = [
    'LPM',
    'PP<125CC',
    'PP>125CC',
    'AT LPM',
    'AT STD',
    'AT STYLISH',
    'AT PREM 125',
    'AT PREM 150',
    'SPORT STD',
    'SPORT PREM'
  ];

  static final List<String> kabupaten_area = [
    'ALOR',
    'AMUNTAI',
    'BALANGAN',
    'BALIKPAPAN',
    'BANJARBARU',
    'BANJARMASIN',
    'BANYUWANGI',
    'BARABAI',
    'BATULICIN',
    'BELU',
    'BERAU',
    'BIMA',
    'BOJONEGORO',
    'BONDOWOSO',
    'BONTANG',
    'BUNTOK',
    'ENDE',
    'GRESIK',
    'JEMBER',
    'JOMBANG',
    'KANDANGAN',
    'KAPUAS',
    'KASONGAN',
    'KOTABARU',
    'LAMONGAN',
    'LOMBOK BARAT',
    'LOMBOK TENGAH',
    'LOMBOK TIMUR',
    'LOMBOK UTARA',
    'LUMAJANG',
    'MADURA',
    'MANGGARAI',
    'MARTAPURA',
    'MATARAM',
    'MELAK',
    'MLG KAB',
    'MLG KOTA',
    'MOJOKERTO',
    'MUARA TEWEH',
    'NTT',
    'NUNUKAN',
    'PALANGKARAYA',
    'PANGKALAN BUN',
    'PASURUAN',
    'PELAIHARI',
    'PROBOLINGGO',
    'PURUKCAHU',
    'RANTAU',
    'SAMARINDA',
    'SAMPIT',
    'SANGATTA',
    'SIDOARJO',
    'SIKKA',
    'SITUBONDO',
    'SUMBA TIMUR',
    'SUMBAWA',
    'SURABAYA',
    'TANAH GROGOT',
    'TANJUNG',
    'TARAKAN',
    'TENGGARONG',
    'TJ. SELOR',
    'TUBAN'
  ];

  static final List<String> services = [
    'STU By Leasing Area',
    'STU By Kab',
    'STU By Kategori DP',
    'STU By Leasing Category',
    'STU By Category Total',
    'STU By Date'
  ];

  static final List<String> Leasing = [
    'BAF',
    'ADIRA',
    'SOF',
    'IMFI',
    'MANDALA',
    'MF',
    'MAF',
    'WOM',
    'CSF',
    'MUF',
    'OTHER'
  ];

  static final List<String> TipeMotor = [
    'AEROX',
    'AEROX 155 VVA',
    'AEROX 155 VVA DOXOU',
    'AEROX 155 VVA GP',
    'AEROX 155 VVA GP - MONSTER',
    'AEROX 155 VVA R VERSION',
    'AEROX 155 VVA S VERSION',
    'AEROX GP MOVISTAR',
    'ALL NEW AEROX 155 CONNECTED CYBERCITY',
    'ALL NEW AEROX 155 VVA',
    'ALL NEW AEROX 155 VVA ABS',
    'ALL NEW AEROX 155 VVA ABS GP',
    'ALL NEW AEROX 155 VVA ABS WGP 60TH',
    'ALL NEW NMAX 155',
    'ALL NEW NMAX 155 ABS',
    'ALL NEW NMAX 155 CONNECTED',
    'ALL NEW R15 155 VVA',
    'ALL NEW R15 155 VVA GP',
    'ALL NEW R15 155 VVA GP - MONSTER',
    'ALL NEW R15 ABS CONNECTED',
    'ALL NEW R15 ABS CONNECTED WGP',
    'ALL NEW R15 CONNECTED',
    'ALL NEW SOUL GT',
    'ALL NEW SOUL GT AKS',
    'ALL NEW SOUL GT AKS SSS',
    'ALL NEW VIXION',
    'ALL NEW VIXION GP',
    'ALL NEW VIXION GP - MONSTER',
    'ALL NEW VIXION R',
    'ALL NEW X-RIDE 125',
    'BYSON',
    'F1ZR',
    'FAZZIO LUX',
    'FAZZIO NEO',
    'FINO CLASSIC',
    'FINO FASHION',
    'FINO GRANDE 125',
    'FINO PREMIUM FI',
    'FINO SPORTY',
    'FINO SPORTY FI',
    'FORCE',
    'FORCE ELEGANT',
    'FREE GO',
    'FREE GO 125',
    'FREE GO 125 CONNECTED',
    'FREE GO S',
    'FREE GO S ABS',
    'GEAR 125',
    'GEAR 125 S',
    'GRAND FILANO LUX',
    'GRAND FILANO NEO',
    'GT 125',
    'GT 125 GARUDA',
    'JUP MX CW NEW',
    'JUPITER MX 150',
    'JUPITER MX CW',
    'JUPITER Z CW',
    'JUPITER Z1 CW FI',
    'JUPITER Z1 FI',
    'JUPITER Z1 FURIOUS',
    'JUPITERMXATCW NEW',
    'LEXAM',
    'LEXI',
    'LEXI ABS',
    'LEXI S',
    'MIO',
    'MIO CW',
    'MIO CW SE',
    'MIO GT',
    'MIO GT GP',
    'MIO J CW',
    'MIO J CW FI TEEN',
    'MIO J FI',
    'MIO M3 AKS SSS',
    'MIO S',
    'MIO SOUL',
    'MIO Z',
    'MT09',
    'MT15',
    'MT25',
    'MT25 NEW (B9T100)',
    'MX KING 150',
    'MX KING 150 DOXOU',
    'MX KING 150 GP',
    'MX KING 150 GP - MONSTER',
    'MX KING WGP 60TH',
    'NEW BYSON FI',
    'NEW FINO PREMIUM 125',
    'NEW FINO SPORTY 125',
    'NEW MIO M3 CW',
    'NEW MIO M3 SP',
    'NEW VIXION (SE)',
    'NEW VIXION ADVANCE',
    'NEW VIXION ADVANCEGP',
    'NEW VIXION GP',
    'NMAX',
    'NMAX ABS',
    'SCORPIO Z CW',
    'SCORPIO Z LE',
    'SOUL GT',
    'SOUL GT STREET',
    'V-IXION',
    'VEGA FORCE DB CW',
    'VEGA FORCE DB SW',
    'VEGA RR',
    'VEGA RR DB',
    'VEGA ZR',
    'VEGA ZRD',
    'WR155',
    'WR155 GP',
    'X MAX CONNECTED',
    'X-RIDE',
    'X-RIDE (ASE)',
    'X-RIDE (SE)',
    'XABRE',
    'XEON',
    'XEON RC',
    'XMAX',
    'XSR',
    'XSR WGP',
    'YZF-R15',
    'YZF-R15 GP MOVISTAR',
    'YZF-R25',
    'YZF-R25 ABS',
    'YZF-R25 ABS WGP',
    'YZF-R25 GP',
    'YZF-R25 GP MOVISTAR',
    'YZF-R25 GP TECH 3'
  ];

  static List<Map<String, dynamic>> motorListMap = TipeMotor.map((motor) {
    return {"name": motor, "value": true};
  }).toList();

  static final List<String> groupName = [
    'CENTRAL',
    'ID JEMBER',
    'ID KALSEL',
    'ID KALTENG',
    'ID KALTIM',
    'ID MALANG',
    'ID NTB',
    'ID SURABAYA',
    'INDO PERKASA',
    'IP JEMBER',
    'IP NTB',
    'KARTIKA GROUP',
    'KARUNIA GROUP',
    'METRO MOTOR',
    'PUSAT GROUP',
    'SINAR UTAMA',
    'SIP JEMBER',
    'SIP KALSEL',
    'SIP KALTENG',
    'SIP KALTIM',
    'SIP MALANG',
    'SIP NTB',
    'SIP SURABAYA',
    'SMA',
    'SUMBER KARYA',
    'TRISAKTI GROUP',
    'TUGU MAS',
    'UNION',
    'UTAMA',
    'YES GROUP NTT',
    'YES GROUP SBY'
  ];

  // static List<Map<String, dynamic>> motorListGroup = groupName.map((motor) {
  //   return {"name": motor, "value": true};
  // }).toList();

  static final List<String> tahunMotor = [
    "BELOW 2018",
    "2024",
    "2023",
    "2022",
    "2021",
    "2020",
    "2019",
  ];
}
